more fixes re psl launch scripts
git-svn-id: https://svn.code.sf.net/p/reduce-algebra/code/trunk@216 2bfe0521-f11c-4a00-b80e-6202646ff360

diff --git a/bin/redpslw b/bin/redpslw
--- a/bin/redpslw
+++ b/bin/redpslw
@@ -1,1 +1,32 @@
-exec $here/../scripts/runpsl.sh bpsl redpsl $*
+a=$0
+c=unknown
+case $a in
+/* )
+  c=$a  
+  ;;
+*/* )
+  case $a in
+  ./* )
+    a=${a#./}
+    ;;
+  esac
+  c=`pwd`/$a
+  ;;
+* ) 
+  for d in $PATH
+  do
+    if test -x $d/$a
+    then
+      c=$d/$a
+    fi
+  done
+  if test $c = "unknown" ;then
+    echo "Unable to find full path for script. Please re-try"
+    echo "launching it using a fully rooted path."
+    exit 1
+  fi
+  ;;
+esac
+
+here=${c%/*}
+exec $here/../scripts/runpsl.sh bpslw redpsl $*
