A new attempt to arrange that autoconf-related files are re-generated in a manner that copes with cross platform and cross-version issues.
git-svn-id: https://svn.code.sf.net/p/reduce-algebra/code/trunk@3399 2bfe0521-f11c-4a00-b80e-6202646ff360

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1819,17 +1819,20 @@ fi
 # (eg -Wno-portability, no-dist-gzip) but even when I removed them
 # it behaved badly for me. However FC2 with autoconf 2.59 and automake
 # 1.8.3 gave me MANY warning messages (eg about underquoted arguments in the
-# m4 scripts) but allowed me to continue. So I set that level as my
-# baseline and ask everybody to install software newer that late 2003.
+# m4 scripts) but allowed me to continue. So I set 2.61 as my
+# baseline since that is better behaved.
+#
+# Well now it is 2016, and I have moved my reliance on to automake 1.13,
+# which was released at the end of 2012. The reason for this move is because
+# I wish to use libtool, and full libtool integration and support for
+# AC_CONFIG_MACRO_DIRS (please note "DIRS" not "DIR" here) date from then.
+# So earlier systems may need a private copy of autoconf installed.
 #
 # If necessary they can fetch source versions of autoconf and automake and
-# install private versions for use here.
-# HOWEVER since the subversion repository for Reduce contains ready build
-# configuration files there should only even be an attempt to rerun
-# autoconf etc if time-stamps get out of order. There is a script
-# .../trunk/scripts/stamp.sh that should restore them. So any user who only
-# has ancient versions of autoconf and automake available is advised to run
-# scripts/stamp.sh after each time they go "svn update".
+# install private versions for use here. Following discussions with other
+# developers I am now going to require autoconf, automake and libtool
+# availability, although an enthusiastic person could probably get things
+# working without them.
 
 
 
@@ -1848,17 +1851,41 @@ $as_echo "$as_me: Absolute path to source directory = $abssrcdir" >&6;}
 # 	automake
 # Note: automake calls libtool for you when necessary.
 
-if ! test $srcdir/aclocal.m4 -nt $srcdir/configure.ac || \
-   ! test $srcdir/Makefile.in -nt $srcdir/aclocal.m4 || \
-   ! test $srcdir/Makefile.in -nt $srcdir/Makefile.am || \
-   ! test $srcdir/configure -nt $srcdir/aclocal.m4
+need="no"
+
+if ! test $srcdir/Makefile.in -nt $srcdir/configure.ac
 then
-  echo "autoreconf necessary I think $ac_configure_args"
+  printf "Makefile.in depends on configure.ac\n"
+  need="yes"
+fi
+if ! test $srcdir/Makefile.in -nt $srcdir/Makefile.am
+then
+  printf "Makefile.in depends on Makefile.am\n"
+  need="yes"
+fi
+if ! test $srcdir/configure -nt $srcdir/configure.ac
+then
+  printf "configure depends on configure.ac\n"
+  need="yes"
+fi
+
+if test "x$need" = "xyes\n"
+then
+  printf "autoreconf necessary (args: $ac_configure_args)\n"
+
   here=`pwd`
   cd $srcdir
+  printf "autoreconf in the top-level directory\n"
   autoreconf -f -i -v
+
   cd $here
-  echo "Restart: $srcdir/configure $ac_configure_args"
+# Because autoconf might not be available or might fail and because I
+# believe I have observed cases where it has not reset timestamps in the
+# way I expected I will reset timestamps explicitly here...
+
+  touch $srcdir/Makefile.am $srcdir/configure
+
+  printf "Restart: $srcdir/configure $ac_configure_args\n"
   exec /bin/sh -c "$srcdir/configure $ac_configure_args"
 fi
 
diff --git a/csl/configure b/csl/configure
--- a/csl/configure
+++ b/csl/configure
@@ -2501,6 +2501,7 @@ ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $
 ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
 
+
 am__api_version='1.14'
 
 ac_aux_dir=
@@ -3114,6 +3115,44 @@ if test -x /bin/sh
 then
   SHELL=/bin/sh
   export SHELL
+fi
+
+need="no"
+
+if ! test $srcdir/Makefile.in -nt $srcdir/configure.ac
+then
+  printf "Makefile.in depends on configure.ac\n"
+  need="yes"
+fi
+if ! test $srcdir/Makefile.in -nt $srcdir/Makefile.am
+then
+  printf "Makefile.in depends on Makefile.am\n"
+  need="yes"
+fi
+if ! test $srcdir/configure -nt $srcdir/configure.ac
+then
+  printf "configure depends on configure.ac\n"
+  need="yes"
+fi
+
+if test "x$need" = "xyes\n"
+then
+  printf "autoreconf necessary (args: $ac_configure_args)\n"
+
+  here=`pwd`
+  cd $srcdir
+  printf "autoreconf in the csl directory\n"
+  autoreconf -f -i -v
+
+  cd $here
+# Because autoconf might not be available or might fail and because I
+# believe I have observed cases where it has not reset timestamps in the
+# way I expected I will reset timestamps explicitly here...
+
+  touch $srcdir/Makefile.am $srcdir/configure
+
+  printf "Restart: $srcdir/configure $ac_configure_args\n"
+  exec /bin/sh -c "$srcdir/configure $ac_configure_args"
 fi
 
 # I am going to expect that you have at least this version of autoconf.
diff --git a/csl/cslbase/configure b/csl/cslbase/configure
--- a/csl/cslbase/configure
+++ b/csl/cslbase/configure
@@ -3493,6 +3493,8 @@ END
   fi
 fi
 
+# I will use the older version too.
+
 
 here=`pwd`
 { $as_echo "$as_me:${as_lineno-$LINENO}: +++ Configure in directory $here +++" >&5
@@ -3537,38 +3539,99 @@ ac_config_files="$ac_config_files Makefile"
 # possible cases where configuration files are out of date, but should
 # cope with some of the more common and important cases.
 
-if \
-   ! test $srcdir/Makefile.in -nt $srcdir/configure.ac || \
-   ! test $srcdir/Makefile.in -nt $srcdir/Makefile.am || \
-   ! test $srcdir/configure -nt $srcdir/configure.ac || \
-   ! test $srcdir/crlibm/Makefile.in -nt $srcdir/crlibm/configure.ac || \
-   ! test $srcdir/crlibm/Makefile.in -nt $srcdir/crlibm/Makefile.am || \
-   ! test $srcdir/crlibm/configure -nt $srcdir/crlibm/configure.ac || \
-   ! test $srcdir/gc-7/Makefile.in -nt $srcdir/gc-7/configure.ac || \
-   ! test $srcdir/gc-7/Makefile.in -nt $srcdir/gc-7/Makefile.am || \
-   ! test $srcdir/gc-7/configure -nt $srcdir/gc-7/configure.ac || \
-   ! test $srcdir/gc-7/libatomic_ops/Makefile.in -nt $srcdir/gc-7/libatomic_ops/configure.ac || \
-   ! test $srcdir/gc-7/libatomic_ops/Makefile.in -nt $srcdir/gc-7/libatomic_ops/Makefile.am || \
-   ! test $srcdir/gc-7/libatomic_ops/configure -nt $srcdir/gc-7/libatomic_ops/configure.ac
+need="no"
+
+if ! test $srcdir/Makefile.in -nt $srcdir/configure.ac
 then
-  echo "autoreconf necessary I think $ac_configure_args"
-#
-# For the following to work properly the sequence MUST leave datestamps
-# on files in the order I test for above, which is based on my understanding
-# of what depends on what. However on SOME platforms at least I find that
-# files do not end up properly ordered and I can get an infinite loop
-# of attempred reconfiguration. So for now I withdraw this!
-#
-# here=`pwd`
-# cd $srcdir
-# autoreconf -f -i -v
-# cd crlibm
-# autoreconf -f -i -v
-# cd ../gc-7
-# autoreconf -f -i -v
-# cd $here
-# echo "Restart: $srcdir/configure $ac_configure_args"
-# exec /bin/sh -c "$srcdir/configure $ac_configure_args"
+  printf "Makefile.in depends on configure.ac\n"
+  need="yes"
+fi
+if ! test $srcdir/Makefile.in -nt $srcdir/Makefile.am
+then
+  printf "Makefile.in depends on Makefile.am\n"
+  need="yes"
+fi
+if ! test $srcdir/configure -nt $srcdir/configure.ac
+then
+  printf "configure depends on configure.ac\n"
+  need="yes"
+fi
+
+if ! test $srcdir/crlibm/Makefile.in -nt $srcdir/crlibm/configure.ac
+then
+  printf "crlibm: Makefile.in depends on configure.ac\n"
+  need="yes"
+fi
+if ! test $srcdir/crlibm/Makefile.in -nt $srcdir/crlibm/Makefile.am
+then
+  printf "crlibm: Makefile.in depends on Makefile.am\n"
+  need="yes"
+fi
+if ! test $srcdir/crlibm/configure -nt $srcdir/crlibm/configure.ac
+then
+  printf "crlibm: configure depends on configure.ac\n"
+  need="yes"
+fi
+
+if ! test $srcdir/gc-7/Makefile.in -nt $srcdir/gc-7/configure.ac
+then
+  printf "gc-7: Makefile.in depends on configure.ac\n"
+  need="yes"
+fi
+if ! test $srcdir/gc-7/Makefile.in -nt $srcdir/gc-7/Makefile.am
+then
+  printf "gc-7: Makefile.in depends on Makefile.am\n"
+  need="yes"
+fi
+if ! test $srcdir/gc-7/configure -nt $srcdir/gc-7/configure.ac
+then
+  printf "gc-7: configure depends on configure.ac\n"
+  need="yes"
+fi
+
+if ! test $srcdir/gc-7/libatomic_ops/Makefile.in -nt $srcdir/gc-7/libatomic_ops/configure.ac
+then
+  printf "gc-7/libatomic_ops: Makefile.in depends on configure.ac\n"
+  need="yes"
+fi
+if ! test $srcdir/gc-7/libatomic_ops/Makefile.in -nt $srcdir/gc-7/libatomic_ops/Makefile.am
+then
+  printf "gc-7/libatomic_ops: Makefile.in depends on Makefile.am\n"
+  need="yes"
+fi
+if ! test $srcdir/gc-7/libatomic_ops/configure -nt $srcdir/gc-7/libatomic_ops/configure.ac
+then
+  printf "gc-7/libatomic_ops: configure depends on configure.ac\n"
+  need="yes"
+fi
+
+if test "x$need" = "xyes\n"
+then
+  printf "autoreconf necessary (args: $ac_configure_args)\n"
+
+  here=`pwd`
+  cd $srcdir
+  printf "autoreconf in the cslbase directory\n"
+  autoreconf -f -i -v
+  cd crlibm
+  printf "autoreconf in the crlibm directory\n"
+  autoreconf -f -i -v
+  cd ../gc-7
+  printf "autoreconf in the gc-7 directories\n"
+  autoreconf -f -i -v
+
+  cd $here
+# Because autoconf might not be available or might fail and because I
+# believe I have observed cases where it has not reset timestamps in the
+# way I expected I will reset timestamps explicitly here...
+
+  touch $srcdir/Makefile.am $srcdir/crlibm/Makefile.am \
+    $srcdir/gc-7/Makefile.am $srcdir/gc-7/libatomic_ops/Makefile.am
+  touch $srcdir/configure $srcdir/crlibm/configure \
+    $srcdir/gc-7/configure $srcdir/gc-7/libatomic_ops/configure
+
+  printf "Restart: $srcdir/configure $ac_configure_args\n"
+  exec /bin/sh -c "$srcdir/configure $ac_configure_args"
 fi
 
 # These days I am making all the source files for CSL ones in C++ not C
@@ -5160,6 +5223,10 @@ $as_echo "$enable_test" >&6; }
 
 if test "x$enable_test" = "xyes"
 then
+# I force EXPERIMENT into CPPFLAGS because when u01.cpp to u60.cpp get
+# compiled they do not include config.h and so would otherwise miss out
+# on the option!
+  CPPFLAGS="$CPPFLAGS -DEXPERIMENT=1"
 
 $as_echo "#define EXPERIMENT 1" >>confdefs.h
 
diff --git a/csl/fox/configure b/csl/fox/configure
--- a/csl/fox/configure
+++ b/csl/fox/configure
@@ -3116,17 +3116,41 @@ fi
 # 	automake
 # Note: automake calls libtool for you when necessary.
 
-if ! test $srcdir/aclocal.m4 -nt $srcdir/configure.ac || \
-   ! test $srcdir/Makefile.in -nt $srcdir/aclocal.m4 || \
-   ! test $srcdir/Makefile.in -nt $srcdir/Makefile.am || \
-   ! test $srcdir/configure -nt $srcdir/aclocal.m4
+need="no"
+
+if ! test $srcdir/Makefile.in -nt $srcdir/configure.ac
 then
-  echo "autoreconf necessary I think $ac_configure_args"
+  printf "Makefile.in depends on configure.ac\n"
+  need="yes"
+fi
+if ! test $srcdir/Makefile.in -nt $srcdir/Makefile.am
+then
+  printf "Makefile.in depends on Makefile.am\n"
+  need="yes"
+fi
+if ! test $srcdir/configure -nt $srcdir/configure.ac
+then
+  printf "configure depends on configure.ac\n"
+  need="yes"
+fi
+
+if test "x$need" = "xyes\n"
+then
+  printf "autoreconf necessary (args: $ac_configure_args)\n"
+
   here=`pwd`
   cd $srcdir
+  printf "autoreconf in the FOX directory\n"
   autoreconf -f -i -v
+
   cd $here
-  echo "Restart: $srcdir/configure $ac_configure_args"
+# Because autoconf might not be available or might fail and because I
+# believe I have observed cases where it has not reset timestamps in the
+# way I expected I will reset timestamps explicitly here...
+
+  touch $srcdir/Makefile.am $srcdir/configure
+
+  printf "Restart: $srcdir/configure $ac_configure_args\n"
   exec /bin/sh -c "$srcdir/configure $ac_configure_args"
 fi
 
